### ISSUE TITLE
Gradle task `uploadArchives` is run implicitly

### ISSUE THREAD

**Issue by caseif** [Lexteam/Lorenz#1]
The default Gradle tasks run the `uploadArchives` task implicitly, without it being specifically defined. This makes the project difficult to build on systems without the required configuration.

**Edit:** It also doesn't seem to define a `jar` task. Unless I misunderstand its intention, your Gradle buildfile is very broken.

**Comment by jamierocks** [comment]
Yeah I should do a simple if statement to see if it's building on the jenkins or not.

**Comment by jamierocks** [comment]
Could you check if https://github.com/Lexteam/Lorenz/commit/8207bc3322c46d2bd386be5d3dde53dc68a37984 fixed the problem?

**Comment by caseif** [comment]
Seems to have, although the script still doesn't actually compile an artifact.

**Comment by jamierocks** [comment]
gradle build doesn't work?

**Comment by caseif** [comment]
It runs, but it doesn't actually compile the code.
